import './EditPost.css'
import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { getPost, editPost } from '../../utils/posts'
import ImageUploadField from '../ImageUploadField/ImageUploadField'